### ISSUE TITLE
Fails to run on Colab

### ISSUE THREAD

**Issue by Nihal2409** [elvisyjlin/gym-chrome-dino#2]
It fails to run on Colab with the following error. Could someone help me out here?

---------------------------------------------------------------------------
WebDriverException                        Traceback (most recent call last)
<ipython-input-6-4079d2022a48> in <module>()
----> 1 env = gym.make('ChromeDinoNoBrowser-v0')
      2 #env = make_dino(env, timer=True, frame_stack=True)

7 frames
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/common/service.py in assert_process_still_running(self)
    109             raise WebDriverException(
    110                 'Service %s unexpectedly exited. Status code was: %s'
--> 111                 % (self.path, return_code)
    112             )
    113 

WebDriverException: Message: Service ./chromedriver unexpectedly exited. Status code was: -6

**Comment by SaadBazaz** [comment]
Colab cannot run chromedriver, because the execution is done on a cloud computer at Google. You won't be able to see the GUI anyway.

**Comment by elvisyjlin** [comment]
Thanks @SaadBazaz 
Colab doesn't work. chromedriver is something similar to the Google Chrome browser. You need a local machine or a virtual machine that you have full access to.
